import type { Metadata } from 'next';
import { Lora } from 'next/font/google';
import './globals.css';
import MainLayout from '@/components/layout';

const lora = Lora({
  variable: '--font-lora',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${lora.variable}`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
